#!/usr/bin/env python3
"""
offline_exact_lambda2.py

Reads btp_agent_positions.csv generated by Step 3 ARGoS code and computes
exact graph algebraic connectivity lambda2 for every logged timestep.

Usage:
    cd ~/btp_3d_fresh
    python3 offline_exact_lambda2.py btp_agent_positions.csv

Outputs:
    exact_lambda2_timeseries.csv
    exact_lambda2_plot.png
"""

import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt


def read_positions(path):
    by_step = defaultdict(list)
    with open(path, "r", newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            step = int(float(r["step"]))
            aid = r["agent_id"]
            typ = r["type"]
            x = float(r["x"])
            y = float(r["y"])
            z = float(r["z"])
            by_step[step].append((aid, typ, np.array([x, y, z], dtype=float)))
    return dict(by_step)


def graph_stats(points, graph_radius):
    n = len(points)
    if n <= 1:
        return 0.0, 0, 0.0, 0.0

    A = np.zeros((n, n), dtype=float)

    for i in range(n):
        for j in range(i + 1, n):
            d = np.linalg.norm(points[i] - points[j])
            if d <= graph_radius:
                A[i, j] = 1.0
                A[j, i] = 1.0

    deg = A.sum(axis=1)
    L = np.diag(deg) - A

    eigvals = np.linalg.eigvalsh(L)
    eigvals = np.sort(np.real(eigvals))
    lambda2 = float(eigvals[1]) if len(eigvals) >= 2 else 0.0

    # connected components
    visited = np.zeros(n, dtype=bool)
    comps = []
    for start in range(n):
        if visited[start]:
            continue
        stack = [start]
        visited[start] = True
        comp = []
        while stack:
            u = stack.pop()
            comp.append(u)
            nbrs = np.where(A[u] > 0)[0]
            for v in nbrs:
                if not visited[v]:
                    visited[v] = True
                    stack.append(int(v))
        comps.append(comp)

    num_components = len(comps)
    largest_component_fraction = max(len(c) for c in comps) / n
    min_degree = float(deg.min()) if n else 0.0

    return lambda2, num_components, largest_component_fraction, min_degree


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("positions_csv", help="btp_agent_positions.csv")
    ap.add_argument("--graph-radius", type=float, default=2.05)
    ap.add_argument("--out-prefix", default="exact_lambda2")
    args = ap.parse_args()

    positions_csv = Path(args.positions_csv).expanduser().resolve()
    out_dir = positions_csv.parent

    by_step = read_positions(positions_csv)
    rows = []

    for step in sorted(by_step):
        items = sorted(by_step[step], key=lambda x: x[0])
        pts = [p for _, _, p in items]
        lam2, comps, largest_frac, min_deg = graph_stats(pts, args.graph_radius)
        rows.append({
            "step": step,
            "exact_lambda2": lam2,
            "num_components": comps,
            "largest_component_fraction": largest_frac,
            "min_degree": min_deg,
        })

    out_csv = out_dir / f"{args.out_prefix}_timeseries.csv"
    with open(out_csv, "w", newline="") as f:
        fieldnames = ["step", "exact_lambda2", "num_components", "largest_component_fraction", "min_degree"]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    steps = [r["step"] for r in rows]
    lam2s = [r["exact_lambda2"] for r in rows]
    comps = [r["num_components"] for r in rows]
    min_deg = [r["min_degree"] for r in rows]

    plt.figure(figsize=(10, 6))
    plt.plot(steps, lam2s, label="exact lambda2")
    plt.axhline(0.0, linestyle="--", linewidth=1)
    plt.xlabel("Step")
    plt.ylabel("Exact algebraic connectivity lambda2")
    plt.title("Exact lambda2 from logged agent positions")
    plt.grid(True, alpha=0.25)
    plt.legend()
    plt.tight_layout()
    out_png = out_dir / f"{args.out_prefix}_plot.png"
    plt.savefig(out_png, dpi=200)
    plt.close()

    plt.figure(figsize=(10, 6))
    plt.plot(steps, comps, label="connected components")
    plt.plot(steps, min_deg, label="minimum degree")
    plt.xlabel("Step")
    plt.ylabel("Graph metric")
    plt.title("Connectivity components and minimum degree")
    plt.grid(True, alpha=0.25)
    plt.legend()
    plt.tight_layout()
    out_png2 = out_dir / f"{args.out_prefix}_components_plot.png"
    plt.savefig(out_png2, dpi=200)
    plt.close()

    print(f"Wrote: {out_csv}")
    print(f"Wrote: {out_png}")
    print(f"Wrote: {out_png2}")


if __name__ == "__main__":
    main()
